name: Release Workers

on:
  push:
    paths:
      - 'docs/**'
      - 'workers/**'
      - '.github/workflows/release_workers.yml'

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      get-microsandbox: ${{ steps.filter.outputs.get-microsandbox }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - '.github/workflows/release_workers.yml'
            get-microsandbox:
              - 'workers/get-microsandbox/**'
              - '.github/workflows/release_workers.yml'

  deploy-docs:
    needs: check-changes
    if: needs.check-changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Retype
        run: npm install -g retypeapp
      - name: Build docs
        working-directory: docs
        run: retype build
      - name: Deploy docs.microsandbox.dev
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: docs
          command: pages deploy .retype --commit-dirty=true

  deploy-get-microsandbox:
    needs: check-changes
    if: needs.check-changes.outputs.get-microsandbox == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy docs.microsandbox.dev
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: workers/get-microsandbox
          command: deploy
